Repository Noostak/Noostak_iOS, pull requests merged in 2025-02, with the labels that each got.

#33 [Feat/NST-13] 그룹상세화면 구현
  Noostak_iOS/Noostak_iOS/Domain/Entity/Schedule.swift
  Noostak_iOS/Noostak_iOS/Global/Extension/UIFont+.swift
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/ic_arrow_right.imageset/Contents.json
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/ic_arrow_right.imageset/Vector.svg
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/ic_group_default.imageset/Contents.json
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/ic_group_default.imageset/Supervisor account.svg
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/ic_share.imageset/Contents.json
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/ic_share.imageset/icon_share.svg
  Noostak_iOS/Noostak_iOS/Global/Utils/NSTDateUtility.swift
  Noostak_iOS/Noostak_iOS/Presentation/Dummy/ViewController.swift
  Noostak_iOS/Noostak_iOS/Presentation/GroupDetail/Reactor/ConfirmedCellReactor.swift
  Noostak_iOS/Noostak_iOS/Presentation/GroupDetail/Reactor/GroupDetailReactor.swift
  Noostak_iOS/Noostak_iOS/Presentation/GroupDetail/Reactor/InProgressCellReactor.swift
  Noostak_iOS/Noostak_iOS/Presentation/GroupDetail/View/Cell/ConfirmedCVC.swift
  Noostak_iOS/Noostak_iOS/Presentation/GroupDetail/View/Cell/InProgressCVC.swift
  Noostak_iOS/Noostak_iOS/Presentation/GroupDetail/View/GroupDetailView.swift
  Noostak_iOS/Noostak_iOS/Presentation/GroupDetail/ViewController/GroupDetailViewController.swift
Labels: Feat

#36 [Feat/NST-13] group member 화면 구현완료
  Noostak_iOS/Noostak_iOS/Domain/Entity/Group.swift
  Noostak_iOS/Noostak_iOS/Domain/Entity/User.swift
  Noostak_iOS/Noostak_iOS/Global/Components/LikeButton.swift
  Noostak_iOS/Noostak_iOS/Global/Components/ScheduleCategoryButton.swift
  Noostak_iOS/Noostak_iOS/Global/Extension/UIFont+.swift
  Noostak_iOS/Noostak_iOS/Global/Utils/NSTDateUtility.swift
  Noostak_iOS/Noostak_iOS/Presentation/GroupMember/Reactor/GroupMemberCellReactor.swift
  Noostak_iOS/Noostak_iOS/Presentation/GroupMember/Reactor/GroupMemberReactor.swift
  Noostak_iOS/Noostak_iOS/Presentation/GroupMember/View/Cell/GroupMemberCVC.swift
  Noostak_iOS/Noostak_iOS/Presentation/GroupMember/View/GroupMemberView.swift
  Noostak_iOS/Noostak_iOS/Presentation/GroupMember/ViewController/GroupMemberViewController.swift
Labels: Feat

#32 [Feat/NST-62] #31 AppToast, ToastManager 작성
  Noostak_iOS/Noostak_iOS/Global/Components/AppColorTextField.swift
  Noostak_iOS/Noostak_iOS/Global/Components/AppColorUnderlineTextField.swift
  Noostak_iOS/Noostak_iOS/Global/Components/AppGrayTextField.swift
  Noostak_iOS/Noostak_iOS/Global/Components/AppThemeButton.swift
  Noostak_iOS/Noostak_iOS/Global/Components/AppToastView.swift
  Noostak_iOS/Noostak_iOS/Global/Components/PaddedTextField.swift
  Noostak_iOS/Noostak_iOS/Global/Components/ProfileImagePicker.swift
  Noostak_iOS/Noostak_iOS/Global/Extension/String+.swift
  Noostak_iOS/Noostak_iOS/Global/Utility/ToastManager.swift
Labels: Feat

#39 [Feat/NST-10] #38 회원가입 화면 작성
  Noostak_iOS/Noostak_iOS/Domain/UseCase/UserUseCase.swift
  Noostak_iOS/Noostak_iOS/Domain/UseCase/Validator/SignUpValidator.swift
  Noostak_iOS/Noostak_iOS/Domain/UseCase/Validator/ValidationResult.swift
  Noostak_iOS/Noostak_iOS/Global/Components/AppColorUnderlineTextField.swift
  Noostak_iOS/Noostak_iOS/Global/Components/AppThemeButton.swift
  Noostak_iOS/Noostak_iOS/Global/Components/ProfileImagePicker.swift
  Noostak_iOS/Noostak_iOS/Global/Components/TextField/AppColorTextField.swift
  Noostak_iOS/Noostak_iOS/Global/Components/TextField/AppColorUnderlineTextField.swift
  Noostak_iOS/Noostak_iOS/Global/Components/TextField/AppGrayTextField.swift
  Noostak_iOS/Noostak_iOS/Global/Components/TextField/PaddedTextField.swift
  Noostak_iOS/Noostak_iOS/Global/Extension/UIViewController+.swift
  Noostak_iOS/Noostak_iOS/Presentation/SignUp/Reactor/SignUpReactor.swift
  Noostak_iOS/Noostak_iOS/Presentation/SignUp/View/SignUpView.swift
  Noostak_iOS/Noostak_iOS/Presentation/SignUp/ViewController/SignUpViewController.swift
Labels: Feat

#40 [Feat/NST-10] #38 회원가입 완료화면 작성
  Noostak_iOS/Noostak_iOS/Global/Components/AppThemeButton.swift
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/Image/img_group_code.imageset/Contents.json
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/Image/img_group_code.imageset/img_group_code.png
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/Image/img_group_code.imageset/img_group_code@2x.png
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/Image/img_group_code.imageset/img_group_code@3x.png
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/Image/img_group_pen.imageset/Contents.json
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/Image/img_group_pen.imageset/img_group_pen.png
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/Image/img_group_pen.imageset/img_group_pen@2x.png
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/Image/img_group_pen.imageset/img_group_pen@3x.png
  Noostak_iOS/Noostak_iOS/Presentation/SignUpComplete/Reactor/SignUpCompleteReactor.swift
  Noostak_iOS/Noostak_iOS/Presentation/SignUpComplete/View/SignUpCompleteView.swift
  Noostak_iOS/Noostak_iOS/Presentation/SignUpComplete/ViewController/SignUpCompleteViewController.swift
Labels: Feat

#43 [Fix/NST-00] gitignore, 구조 수정
  .gitignore
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/Icon/Contents.json
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/Icon/icn_profile_camera.imageset/Contents.json
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/Icon/icn_profile_camera.imageset/icn_profile_camera.svg
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/Icon/icn_textfield_delete_24.imageset/Contents.json
  Noostak_iOS/Noostak_iOS/Global/Resources/Assets.xcassets/Icon/icn_textfield_delete_24.imageset/_icn_textfield_delete_24.svg
  Noostak_iOS/Noostak_iOS/Global/Utility/NSTDateUtility.swift
Labels: Fix

#45 [Add ]#44 - 필요한 유틸 기능 추가 했습니다.
  Noostak_iOS/Noostak_iOS/Global/Extension/UIView+.swift
  Noostak_iOS/Noostak_iOS/Global/Extension/getClassName.swift
Labels: Add
